---
title: "post3"
output: html_document
---

This chapter continued the conversation about how data feminism can be used to challenge power structures and foster discussion about how data science has been used to oppressive minority groups. What stuck out from this chapter was what was said about wealth was attached to the category of whiteness and how data science was just a tool that played a role in preserving that. Looking at the history of the United States, the way the laws that have been created exclude marginalized groups like women and people of color from fully having equal rights and gaining wealth. In this chapter, it talked about how the wealth inequality between white and black people has been affected by the systems or algorithms that perpetuate the bias that exists in society. What is interesting about these systems is that race is rarely ever a specified factor. Usually other things like the makeup of someone’s household or their home address can be used as racial indicators. Systems like FICO scores, that determine a person’s financial trustworthiness, have been biased against black Americans. Because of other systems like redlining, it has been more difficult for generations of black Americans to obtain more wealth and have socioeconomic mobility.  It is safe to assume that the people that created these systems did not mean to specifically harm certain groups of people, but the way these systems have affected people shows how race impacts every facet of our society.