---
title: "Blog Post 1"
---

This chapter made me think about how marginalized people are almost always doing the necessary work to undo injustices in society. It was rare that people in power try to undo systems that benefit them. Feminist work was produced by women who wanted a better life and fought for people to see through their society’s oppressive systems. By building coalitions to fight against systematic oppression, feminists created a space for people to question hierarchical systems. This chapter centers around Christine Darden, a data analyst who worked for NASA and whose activism led to great advancements in both data science and the feminist movement. This chapter talks about the questionable origins of data science and how data science has been used historically to justify the subjugation of marginalized groups. The authors state that data science could be used to create positive change by looking at data through an intersectional lens and using it to fight against systematic issues. A part of this reading that stuck out to me was when they stated that data feminism could use the standard practices in data science that serve to reinforce these existing inequalities to challenge and change the distribution of power. This made me think about an organization like Data for Black Lives that uses data science to fight against structural issues that affect communities of color. In this chapter, it talks about how big data and emerging technologies have been used to disproportionately discriminate against low-income or minority groups. Data for Black Lives is one example of an organization that is using tools like statistical modeling, data visualization, and crowd-sourcing to fight against bias and promote change.