---
title: "Blog Post 4"
---

This chapter talks about data science and its role in perpetuating the gender binary. Usually legal applications or even websites that require people to list their gender rarely have any other options than male or female. In the past few years, many organizations like Facebook have been trying to be more socially aware by allowing users to input their own gender instead of having to choose one from a select list. Other organizations that have decided to be more gender inclusive have created more options for people to choose from. Even though the field of data science is putting more of an effort to be more inclusive, isn’t creating more categories for gender and asking gender noncomforming/nonbinary people to select or describe their gender in a specific way forcing them to stay within the gender binary? It is interesting to think about what data science would look like without binaries, because everything in data science is binary. In order to produce analysis and create data, things have to be put into categories. Data science can never truly explain all of the differences people might have based on their gender, sexual identity, race, or class. After reading this chapter, I thought about how almost every classification of humans that is used in data science does not have an inherent meaning. What data science measures is how people’s identities impact them in a systematic way. This discussion about gender inclusivity is making me think about how many patterns were not unseen or how many people were left uncounted because their identities were misrepresented.